version: "3.7"

services:
  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "some_password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_DB: petclinic

  petclinic:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/petclinic?useSSL=falseallowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_PROFILES_ACTIVE: "mysql"

